name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ทำงานเมื่อมีการ push ไปที่สาขา main

jobs:
  build:
    runs-on: ubuntu-latest  # รันบน Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # ดึงโค้ดจาก GitHub repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # กำหนดเวอร์ชัน Python ที่ต้องการ

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # ติดตั้ง dependencies ที่ระบุใน requirements.txt
          pip install pytest  # ติดตั้ง pytest ถ้าต้องการในขั้นตอนนี้

      - name: Deploy (Optional)
        run: |
          echo "Deploying to the server... !!!!"  # ใส่คำสั่งสำหรับ deployment ที่ต้องการ เช่น SCP, SSH เป็นต้น
